name: Run tests
on: push
jobs:
  run-shell-command:
     runs-on: ubuntu-latest
     steps:
       -uses: actions/checkout@v2
       -name: install dependencies
        run: |
          python -m pip install -upgrade pip
          pip install -r requirements.txt
       - name: run tests
        run: python -m unittest discover ./tests
       - name: run type cheking
        run: mypy fib_max_py
